# Generated by Django 4.1.7 on 2023-02-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_alter_lead_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.userprofile",
            ),
            preserve_default=False,
        ),
    ]
